using System;
using AtividadesDeCsharp;

//Antecessor.Main(args);
//AreaQuadrado.Main(args);
//AreaRetangulo.Main(args);
//AreaLosango.Main(args);
//AreaCirculo.Main(args);
//Faccat07.Main(args);
//Faccat08.Main(args);
//Faccat09.Main(args);
//Faccat10.Main(args);
//Faccat11.Main(args);
//IfTernario.Main(args);
//IfTernario02.Main(args);
//SwitchCase.Main(args);
//MesSwitchCase.Main(args);
//ExemploWhile.Main(args);
//L03A.Main(args);
//L03B.Main(args);
L03C.Main(args);